name: Dockerhub Publish

on:
  push:
    branches:
      - main 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t secrets.DOCKERHUB_USERNAME/sharpmaid:latest .
          docker push secrets.DOCKERHUB_USERNAME/sharpmaid:latest
